### ISSUE TITLE
Crash After Death

### ISSUE THREAD

**Issue by WenXin20** [Eragonn1490/Reactioncraft-1.12.2#13]
Forge v14.23.4.2707-1.12.2
ReactionCraft 3 v0.7.0.0-PR
I got a crash w/ this mod after a creeper exploded and killed me.
[Crash Report](https://gist.github.com/WenXin20/a0b0ee790860710b49bc093738d02c14)

**Comment by Eragonn1490** [comment]
@WenXin20 its fixed (im verifying it now) and will be uploaded shortly
